version: '3'

services:
  # php
  php:
    build: ./docker/php
    volumes:
      - ./src:/data
      - ./docker/php/php.development.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
      - node
  # nginx
  web:
    build: ./docker/nginx
    ports: 
      - 80:80
    volumes:
      - ./src:/data
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - node
  # MySQL
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: schedule
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306
  ## python3 
  python3:
    restart: always
    build: ./docker/python
    working_dir: "/root/opt/"
    tty: true
    volumes:
      - ./opt:/root/opt
    depends_on:
      - selenium
  ## selenium 
  selenium:
    image: selenium/standalone-chrome:4.0.0-rc-1-prerelease-20210804
    shm_size: 2gb
    ports:
      - 4444:4444
      - 7900:7900
    volumes:
      - /dev/shm:/dev/shm
  ## node
  node:
    image: node:16-alpine
    working_dir: /data
    tty: true
    ports:
      - 5173:5173
    volumes:
      - ./src:/data
    command:
      sh -c "npm install && npm run dev"
volumes:
  mysql-data:
